#!/usr/bin/env bash
#NOTE: working
sessions=$(tmux list-sessions -F "#{session_name}")
if [[ -z "$sessions" ]]; then
    echo "No tmux sessions available."
    exit 0
fi

session=$(echo "$sessions" | fzf \
    --bind "ctrl-l:execute(tmux kill-session -t {1} && echo 'Killed {1}')+reload(tmux list-sessions -F '#{session_name}')")

[[ -z "$session" ]] && exit 0

if [[ -n "$TMUX" ]]; then
    tmux switch-client -t "$session"
else
    tmux attach -t "$session"
fi

